language: python
matrix:
  global:
    LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
  include:
    - python: "2.7"
      env: TOXENV=py27
    - python: "3.5"
      env: TOXENV=py35
    - python: "3.6"
      env: TOXENV=py36,coveralls, docs
    - python: "pypy"
      env: TOXENV=pypy

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libpcap-dev
  - python --version
  - virtualenv --version
  - pip --version
  - uname -a
  - lsb_release -a
install:
  - pip install tox
script:
  - tox -e $TOXENV
notifications:
  email:
    on_success: never
    on_failure: always
webhooks:
  urls:
    - https://webhooks.gitter.im/e/0afdfbd1699a27b502d5
  on_success: change  # options: [always|never|change] default: always
  on_failure: always  # options: [always|never|change] default: always
