language: python
python: 2.7
env:
  global:
    LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
  matrix:
    - TOXENV=py26,coveralls
    - TOXENV=py27,coveralls
    - TOXENV=pypy,coveralls
    - TOXENV=docs
before_install:
  - sudo apt-get install libpcap0.8
  - python --version
  - virtualenv --version
  - pip --version
  - uname -a
  - lsb_release -a
install:
  - pip install tox
script:
  - tox -v
notifications:
  email:
    on_success: never
    on_failure: always

